from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER
from sqlalchemy.orm import Session
from fastapi import HTTPException

from app.database import SessionLocal
from app.models.chat_message_model import ChatMessage
from app.models.chat_session_model import ChatSession


class ExportService:

    @staticmethod
    def export_session_pdf(session_id: str, user_id: str) -> bytes:
        db: Session = SessionLocal()
        try:
            session = db.query(ChatSession).filter(
                ChatSession.id == session_id,
                ChatSession.user_id == user_id
            ).first()

            if not session:
                raise HTTPException(status_code=404, detail="Chat session not found.")

            messages = db.query(ChatMessage).filter(
                ChatMessage.session_id == session_id
            ).order_by(ChatMessage.created_at.asc()).all()

        finally:
            db.close()

        buffer = BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=2 * cm,
            leftMargin=2 * cm,
            topMargin=2 * cm,
            bottomMargin=2 * cm,
        )

        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            "Title",
            parent=styles["Heading1"],
            fontSize=18,
            textColor=colors.HexColor("#0f172a"),
            spaceAfter=6,
            alignment=TA_LEFT,
        )
        subtitle_style = ParagraphStyle(
            "Subtitle",
            parent=styles["Normal"],
            fontSize=10,
            textColor=colors.HexColor("#64748b"),
            spaceAfter=16,
        )
        user_label_style = ParagraphStyle(
            "UserLabel",
            parent=styles["Normal"],
            fontSize=9,
            textColor=colors.HexColor("#059669"),
            fontName="Helvetica-Bold",
            spaceAfter=2,
        )
        ai_label_style = ParagraphStyle(
            "AILabel",
            parent=styles["Normal"],
            fontSize=9,
            textColor=colors.HexColor("#3b82f6"),
            fontName="Helvetica-Bold",
            spaceAfter=2,
        )
        message_style = ParagraphStyle(
            "Message",
            parent=styles["Normal"],
            fontSize=10,
            textColor=colors.HexColor("#1e293b"),
            leading=14,
            spaceAfter=12,
        )

        story = []

        # Header
        story.append(Paragraph("NeuralStack AI", title_style))
        story.append(Paragraph(f"Chat Export — {session.session_name or 'Session'}", subtitle_style))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0")))
        story.append(Spacer(1, 0.4 * cm))

        if not messages:
            story.append(Paragraph("No messages in this session.", message_style))
        else:
            for msg in messages:
                if msg.sender == "user":
                    story.append(Paragraph("You", user_label_style))
                else:
                    story.append(Paragraph("NeuralStack AI", ai_label_style))

                # Clean text — reportlab needs escaped characters
                text = (msg.message_text or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                story.append(Paragraph(text, message_style))

        # Footer
        story.append(Spacer(1, 0.5 * cm))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e2e8f0")))
        story.append(Paragraph(
            "Generated by NeuralStack AI · neuralstack.ai",
            ParagraphStyle("Footer", parent=styles["Normal"],
                          fontSize=8, textColor=colors.HexColor("#94a3b8"), alignment=TA_CENTER)
        ))

        doc.build(story)
        return buffer.getvalue()
